### ISSUE TITLE
macsOS dependencies missing

### ISSUE THREAD

**Issue by NikolausDemmel** [gisogrimm/ovbox#4]
I just tried compiling on macOS according to the wiki instructions: https://github.com/gisogrimm/ovbox/wiki/Installation#compile-yourself

It looks like two dependencies were missing: `libltc libmatio`

PS: I tried editing the wiki page to add them. I though it would open a PR or something, but looks like it saved the page :-). So I guess you can close this issue.

**Comment by gisogrimm** [comment]
Thank you for the addition. On top of it I added a reference to the current github workflow files for MacOS, which are continuously maintained.
